# Generated by Django 3.2.3 on 2021-07-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FanInsert',
            new_name='FanProfile',
        ),
    ]
