# Generated by Django 3.2.3 on 2021-07-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_rename_faninsert_fanprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchentrace',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='matchentrace',
            name='mzunguko_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchentrace',
            name='platnum_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchentrace',
            name='vip_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fanprofile',
            name='status',
            field=models.CharField(choices=[('SAFE', 'SAFE'), ('BURNED', 'BURNED')], max_length=255, null=True),
        ),
    ]
