# Generated by Django 3.2.3 on 2021-07-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20210707_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchentrace',
            name='price',
        ),
    ]
