# Generated by Django 3.2.3 on 2021-07-08 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_alter_matchentrace_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchentrace',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='entrace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.matchentrace'),
        ),
    ]
