# Generated by Django 3.2.3 on 2021-07-08 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_payment_due_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.match'),
        ),
    ]
