# Generated by Django 3.2.3 on 2021-07-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_alter_ticket_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
