# Generated by Django 3.2.3 on 2021-07-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_ticket_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payed',
            field=models.CharField(choices=[('Payed', 'Payed'), ('Not Payed', 'Not Payed')], default='False', max_length=244),
        ),
    ]
