# Generated by Django 3.2.3 on 2021-08-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0014_alter_ticket_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='fans_no',
        ),
    ]
